create DATABASE GROUP_BY_PRACTICE;
USE GROUP_BY_PRACTICE;

CREATE TABLE sales (
    sale_id INT,
    customer VARCHAR(50),
    city VARCHAR(50),
    product VARCHAR(50),
    category VARCHAR(50),
    quantity INT,
    price INT
);

INSERT INTO sales
(sale_id, customer, city, product, category, quantity, price)
VALUES
(1, 'Ali', 'Karachi', 'Laptop', 'Electronics', 2, 80000),
(2, 'Ahmed', 'Lahore', 'Mouse', 'Electronics', 5, 1500),
(3, 'Sara', 'Karachi', 'Keyboard', 'Electronics', 3, 3000),
(4, 'Hamza', 'Islamabad', 'Laptop', 'Electronics', 1, 80000),
(5, 'Ali', 'Karachi', 'Monitor', 'Electronics', 2, 25000),
(6, 'Sara', 'Lahore', 'Chair', 'Furniture', 4, 12000),
(7, 'Ahmed', 'Lahore', 'Desk', 'Furniture', 2, 20000),
(8, 'Hamza', 'Islamabad', 'Mouse', 'Electronics', 6, 1500),
(9, 'Ali', 'Karachi', 'Chair', 'Furniture', 2, 12000),
(10, 'Sara', 'Lahore', 'Laptop', 'Electronics', 1, 80000),
(11, 'Ahmed', 'Lahore', 'Keyboard', 'Electronics', 4, 3000),
(12, 'Hamza', 'Islamabad', 'Desk', 'Furniture', 3, 20000),
(13, 'Ali', 'Karachi', 'Mouse', 'Electronics', 10, 1500),
(14, 'Sara', 'Lahore', 'Monitor', 'Electronics', 2, 25000),
(15, 'Hamza', 'Islamabad', 'Chair', 'Furniture', 5, 12000),
(16, 'Usman', 'Karachi', 'Laptop', 'Electronics', 1, 80000),
(17, 'Ayesha', 'Lahore', 'Mouse', 'Electronics', 8, 1500),
(18, 'Bilal', 'Islamabad', 'Keyboard', 'Electronics', 2, 3000),
(19, 'Ali', 'Karachi', 'Desk', 'Furniture', 1, 20000),
(20, 'Ahmed', 'Lahore', 'Monitor', 'Electronics', 3, 25000),
(21, 'Sara', 'Karachi', 'Chair', 'Furniture', 2, 12000),
(22, 'Hamza', 'Islamabad', 'Laptop', 'Electronics', 2, 80000),
(23, 'Usman', 'Karachi', 'Mouse', 'Electronics', 7, 1500),
(24, 'Ayesha', 'Lahore', 'Desk', 'Furniture', 4, 20000),
(25, 'Bilal', 'Islamabad', 'Monitor', 'Electronics', 1, 25000),
(26, 'Ali', 'Karachi', 'Keyboard', 'Electronics', 5, 3000),
(27, 'Ahmed', 'Lahore', 'Chair', 'Furniture', 3, 12000),
(28, 'Sara', 'Karachi', 'Laptop', 'Electronics', 1, 80000),
(29, 'Hamza', 'Islamabad', 'Mouse', 'Electronics', 9, 1500),
(30, 'Usman', 'Karachi', 'Desk', 'Furniture', 2, 20000);



select * from sales;
#q1
select city , sum(quantity) as total_quantity
from sales
group by city;

#q2 : Find the number of sales made by each customer and show the customer with the highest number of sales first.

select customer , sum(price) as sales_count
from sales
group by customer 
order by sum(price) desc;


#q3 :find the average price of products in each category.


select category , round(avg(price) , 2 )as averae_price
from sales
group by category ;


#q4 :Find the total revenue generated by each city.

select city , sum( price * quantity) as total_revenue
from sales 
group by city ;

#q5 :Find cities where the total quantity sold is greater than 15.

select city , sum(quantity) as total_quantity
from sales
group by city 
having total_quantity > 15;


#q6 :Find customers whose total quantity sold is greater than 10, and arrange them from highest to lowest quantity

select customer , sum(quantity) as total_quantity
from sales 
group by customer
having total_quantity >10
order by total_quantity desc;


#q7 :Find the most expensive product price for each category.

select category , max(price) as max_price
from sales
group by category;

#q8 : Find the total revenue for each product and show only products with revenue greater than 50,000.

select product , sum(quantity * price) as revenue_per_product
from sales
group by product
having revenue_per_product > 50000
order by revenue_per_product DESC;


#q9 : Find the number of different customers in each city.

select city ,count(distinct customer) as customer_per_city 
from sales
group by city;


#q11 : Find the top 3 customers based on total revenue.

select customer , sum(quantity * price) as total_revenue
from sales 
group by customer
order by total_revenue desc
limit 3;


#q12 : Find categories where: 
#Find categories where:

#total quantity > 15
#total revenue > 100,000

select category , sum(quantity) as total_quantity , sum(price * quantity) as revenue 
from sales 
group by category
having total_quantity > 15 AND revenue >100000;

#q13 : Find each customer's total revenue, but only show customers whose revenue is greater than 100,000.

select  customer, sum( quantity * price) as revenue
from sales 
group by customer
having revenue > 100000;


#q14 : Find the city that has the highest total quantity sold.

select city , sum(quantity) as highest_sold
from sales 
group by city
order by highest_sold desc
limit 1;


#q15 : Find the city that has the 2 highest total quantity sold.

select city , sum(quantity) as highest_sold
from sales 
group by city
order by highest_sold desc
limit 1 offset 1;
